apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-blue
  labels:
    app: demo-api
    color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
      color: blue
  template:
    metadata:
      labels:
        app: demo-api
        color: blue
    spec:
      containers:
      - name: api
        image: catalinapenamora/demo-api:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-green
  labels:
    app: demo-api
    color: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
      color: green
  template:
    metadata:
      labels:
        app: demo-api
        color: green
    spec:
      containers:
      - name: api
        image: catalinapenamora/demo-api:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 10