apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: demo-api
  labels:
    app: app
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: blue
  template:
    metadata:
      labels:
        app: app
        version: blue
    spec:
      containers:
      - name: app-contenedor
        image: catalinapenamora/demo-api:latest 
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: app-bg-service
  namespace: demo-api
spec:
  selector:
    app: app
    # El pipeline cambiará dinámicamente este selector entre 'blue' o 'green'
    version: blue 
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: demo-api
  labels:
    app: app
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: green
  template:
    metadata:
      labels:
        app: app
        version: green
    spec:
      containers:
      - name: app-contenedor
        image: catalinapenamora/demo-api:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 10