name: Pipeline de la Aplicacion Consumidora

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Este job no tiene "runs-on" ni "steps", porque todo eso viene del template
  llamar-despliegue-desarrollo:
    # AQUÍ ESTÁ LA MAGIA: Llamamos a tu repositorio Core
    uses: catalinapenamora/SDLC003D-SharedWorkflows-CatalinaPena/.github/workflows/deploy.yaml@main
    with:
      entorno: 'desarrollo'

  llamar-despliegue-produccion:
    needs: llamar-despliegue-desarrollo # Espera a que termine desarrollo
    uses: catalinapenamora/SDLC003D-SharedWorkflows-CatalinaPena/.github/workflows/deploy.yaml@main
    with:
      entorno: 'producción'